apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: test-deployment
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      group: test-pod-default
  template:
    metadata:
      labels:
        group: test-pod-default
    spec:
      schedulerName: default-scheduler
      containers:
      - image: easzlab.io.local:5000/easzlab/pause:3.7
        name: {{.Name}}