# Huge service test config
{{$HUGE_SERVICE_HEADLESS := DefaultParam .CL2_HUGE_SERVICE_HEADLESS false}}
{{$HUGE_SERVICE_ENDPOINTS := DefaultParam .CL2_HUGE_SERVICE_ENDPOINTS 1000}}
{{$STATEFULSET_ENDPOINTS := DefaultParam .CL2_STATEFULSET_ENDPOINTS 100}}
{{$DELETE_NAMESPACE_TIMEOUT := DefaultParam .CL2_DELETE_NAMESPACE_TIMEOUT "10m"}}

name: huge-service
namespace:
  number: 1
  deleteNamespaceTimeout: {{$DELETE_NAMESPACE_TIMEOUT}}
tuningSets:
- name: Sequence
  parallelismLimitedLoad:
    parallelismLimit: 1
steps:
- module:
    path: modules/measurements.yaml
    params:
      action: start
- module:
    path: modules/service.yaml
    params:
      endpoints: {{$HUGE_SERVICE_ENDPOINTS}}
      statefulsetEndpoints: {{$STATEFULSET_ENDPOINTS}}
      isHeadless: {{$HUGE_SERVICE_HEADLESS}}
      serviceName: huge-service
- module:
    path: modules/measurements.yaml
    params:
      action: gather
