apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    test: {{.TestClientLabel}}
spec:
  podSelector:
    matchLabels:
      test: {{.TestClientLabel}}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    to:
    - ipBlock:
        cidr: {{.kubeAPIServerIP}}/32
