apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    type: {{.TypeLabelValue}}
spec:
  podSelector:
    matchLabels:
      type: {{.TypeLabelValue}}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{.TargetLabelKey}}: {{.TargetLabelValue}}
{{if .OnlyTargetNamespace}}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{.TargetNamespace}}
{{else}}
      namespaceSelector: {}
{{end}}
