apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: netperf
  name: worker
  labels:
    group: network
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        group: network
        name: worker
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - worker
            topologyKey: kubernetes.io/hostname
      containers:
      - image: gcr.io/k8s-testimages/netperfbenchmark:0.3
        name: worker
        imagePullPolicy: IfNotPresent
        args:
          - --log_file=/var/log/cl2-netperf-worker.log
          - --logtostderr=false
          - --v=4
          - --udpClientExtraArguments=-b 750M
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "500m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
            - name: logs-volume
              mountPath: /var/log
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log

