apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
type: Opaque
stringData:
# To get 1MB of payload we need:
# 1 mln(bytes)/1.33 (base64 after serialisation is ~30% increase) = ~760K bytes
  password: {{RandData 760000}}
